import "@/styles/globals.css";

import { ThemeSwitcherButton } from "@/components/ui/ThemeSwitcherButton";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Inter } from "next/font/google";
import { type ReactNode } from "react";
import { Providers } from "../../providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "FinTrack",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<LayoutProps>) {
  const messages = await getMessages();

  return (
    <html id="Root" lang={locale} className="dark">
      <head />
      <body className={`antialized min-h-screen font-sans ${inter.variable}`}>
        <Providers>
          <ThemeSwitcherButton className="absolute right-4 top-4" />
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}

type LayoutProps = {
  children: Readonly<ReactNode>;
  params: { locale: string };
};
