import "@/styles/globals.css";

import { Header } from "@/components/ui/Header";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import { Inter } from "next/font/google";
import { type ReactNode } from "react";
import { Providers } from "../../providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "FinTrack",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<LayoutProps>) {
  unstable_setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <html className="h-full" lang={locale}>
      <head />
      <body className={`antialized min-h-screen font-sans ${inter.variable}`}>
        <Analytics />
        <SpeedInsights />
        <Providers>
          <NextIntlClientProvider messages={messages}>
            <Header />
            {children}
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}

type LayoutProps = {
  children: Readonly<ReactNode>;
  params: { locale: string };
};
